### ISSUE TITLE
get_logical file fails for CSVs 

### ISSUE THREAD

**Issue by mansfieldbitter** [OdinProAgrica/hpycc#72]
```Traceback (most recent call last):
  File ".\getECL.py", line 17, in <module>
    chunk_size=100000
  File "C:\ProgramData\Anaconda3\lib\site-packages\hpycc\save.py", line 140, in save_logical_file
    chunk_size, max_attempts)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hpycc\get.py", line 373, in get_logical_file
    for f in finished], ignore_index=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hpycc\get.py", line 373, in <listcomp>
    for f in finished], ignore_index=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hpycc\utils\parsers.py", line 61, in parse_json_output
    df = pd.DataFrame(map(list, zip(*lines)), columns=column_names)
  File "C:\Users\mansfieldr\AppData\Roaming\Python\Python36\site-packages\pandas\core\frame.py", line 334, in __init__
    raise TypeError("data argument can't be an iterator")
TypeError: data argument can't be an iterator
```

**Comment by cqkh42** [comment]
closing as this will be fixed in 0.1.3
